version: ‘3.7’

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
 redis:
  image: redis:alpine
  networks:
   - instavote

 db: 
  image: postgres:9.4
  volumes:
   - "db-data:/var/lib/postgresql/data"
  networks:
   - instavote
  environment:
    POSTGRES_HOST_AUTH_METHOD: trust

 vote:
  image: initcron/vote:master
  build: ./vote
  ports:
   - 5004:80
  depends_on:
   - redis
  networks:
   - instavote
     #links:
     #- redis:redis

 result:
  image: seyibright/result:v1
  build: ./vote
  ports:
   - 5002:4000
  depends_on:
   - db
  networks:
   - instavote
     #links:
     #- db:db

 worker:
  image: seyibright/worker:latest
  build: ./vote
  ports:
   - 5006:80
  depends_on:
   - redis
   - db
  networks:
   - instavote
     #links:
     #- redis:redis
     #- db:db

